"""
Django settings for ideas_backend project.
Generated by 'django-admin startproject' using Django 6.0.2.
"""

import os
from pathlib import Path
from datetime import timedelta
import dj_database_url

# 1. RUTAS DEL PROYECTO
# ----------------------------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

# 2. CONFIGURACIÓN DE SEGURIDAD
# ----------------------------------------------------------------------
# En Render, esto se lee de las Environment Variables. Si no existe, usa la de backup.
SECRET_KEY = os.environ.get("SECRET_KEY", "c^vn=sm%h(%=*7qzvyirty=ijx&ond+cudzjitojnnl72w&g^h")

# DEBUG debe ser False en producción (Render). En tu PC será True.
DEBUG = os.environ.get("DEBUG", "True").lower() == "true"

ALLOWED_HOSTS = ['.onrender.com', 'localhost', '127.0.0.1']

# 3. DEFINICIÓN DE APLICACIONES (INSTALLED_APPS)
# ----------------------------------------------------------------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Apps de terceros
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    
    # Tu App Local
    'api', 
]

# 4. MIDDLEWARE (ORDEN CRÍTICO)
# ----------------------------------------------------------------------
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # CORS siempre primero
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # WhiteNoise para archivos estáticos
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ideas_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ideas_backend.wsgi.application'

# 5. CONFIGURACIÓN DE BASE DE DATOS (HÍBRIDA)
# ----------------------------------------------------------------------
# Esta configuración detecta automáticamente si estás en Render o en tu PC.
# 5. CONFIGURACIÓN DE BASE DE DATOS (HÍBRIDA)
# ----------------------------------------------------------------------
# Render buscará DATABASE_URL (SQLite). Si no existe, usará tu MySQL local.
DATABASES = {
    'default': dj_database_url.config(
        default='mysql://root:Jefri2311.@127.0.0.1:3306/ideas_social',
        conn_max_age=600
    )
}

# ✅ CORRECCIÓN: Solo aplicamos opciones de MySQL si el motor es MySQL
if DATABASES['default'].get('ENGINE') == 'django.db.backends.mysql':
    DATABASES['default']['OPTIONS'] = {
        'charset': 'utf8mb4',
    }
# 6. VALIDACIÓN DE CONTRASEÑAS
# ----------------------------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# 7. INTERNACIONALIZACIÓN
# ----------------------------------------------------------------------
LANGUAGE_CODE = 'es-mx'
TIME_ZONE = 'America/Mexico_City'
USE_I18N = True
USE_TZ = True

# 8. ARCHIVOS ESTÁTICOS Y MULTIMEDIA (PARA RENDER)
# ----------------------------------------------------------------------
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Configuración de almacenamiento para WhiteNoise
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# 9. DJANGO REST FRAMEWORK
# ----------------------------------------------------------------------
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

# 10. CONFIGURACIÓN JWT (SimpleJWT)
# ----------------------------------------------------------------------
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# 11. CONFIGURACIÓN CORS (React comunicándose con Django)
# ----------------------------------------------------------------------
CORS_ALLOW_ALL_ORIGINS = True  # Permitir todos para facilitar el despliegue inicial
CORS_ALLOW_CREDENTIALS = True

# 12. OTROS
# ----------------------------------------------------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'