"""
Django settings for ideas_backend project.
Generated by 'django-admin startproject' using Django 6.0.2.
"""

import os
from pathlib import Path
from datetime import timedelta
import dj_database_url
from django.core.exceptions import ImproperlyConfigured

# 1. RUTAS DEL PROYECTO
# ----------------------------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

# 2. CONFIGURACIÓN DE SEGURIDAD
# ----------------------------------------------------------------------
# DEBUG se lee del entorno y por defecto es False: si la variable falta en
# Render, el comportamiento seguro es arrancar en modo producción, nunca
# exponer el modo debug (trazas, código fuente y URLconf) en internet.
DEBUG = os.environ.get("DEBUG", "False").lower() == "true"

# La SECRET_KEY nunca se escribe en el repositorio. Firma las cookies de
# sesión y, como SIMPLE_JWT no define SIGNING_KEY, firma también los JWT:
# con la clave publicada cualquiera puede falsificar un token de cualquier
# usuario, incluido el superusuario.
SECRET_KEY = os.environ.get("SECRET_KEY")
if not SECRET_KEY:
    if DEBUG:
        # Valor de relleno solo para desarrollo local.
        SECRET_KEY = "django-insecure-solo-para-desarrollo-local"
    else:
        raise ImproperlyConfigured(
            "Falta la variable de entorno SECRET_KEY. Configúrala en Render "
            "(Environment) antes de desplegar."
        )

ALLOWED_HOSTS = ['.onrender.com', 'localhost', '127.0.0.1']

# Render corta el TLS en su proxy y reenvía la petición por HTTP con la
# cabecera X-Forwarded-Proto. Sin esto Django cree que la conexión no es
# segura y, con DEBUG=False, el login del admin falla la comprobación CSRF.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# 3. DEFINICIÓN DE APLICACIONES (INSTALLED_APPS)
# ----------------------------------------------------------------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Apps de terceros
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    
    # Tu App Local
    'api', 
]

# 4. MIDDLEWARE (ORDEN CRÍTICO)
# ----------------------------------------------------------------------
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # CORS siempre primero
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # WhiteNoise para archivos estáticos
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ideas_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ideas_backend.wsgi.application'

# 5. CONFIGURACIÓN DE BASE DE DATOS (HÍBRIDA)
# ----------------------------------------------------------------------
# Esta configuración detecta automáticamente si estás en Render o en tu PC.
# 5. CONFIGURACIÓN DE BASE DE DATOS (HÍBRIDA)
# ----------------------------------------------------------------------
# Render buscará DATABASE_URL (SQLite). Si no existe, usará tu MySQL local.
DATABASES = {
    'default': dj_database_url.config(
        # Sin DATABASE_URL se usa SQLite en el propio proyecto. Antes había
        # aquí un DSN de MySQL con la contraseña en claro, en un repo público.
        default=f"sqlite:///{(BASE_DIR / 'db.sqlite3').as_posix()}",
        conn_max_age=600,
        # Supabase (y su pooler) cierran conexiones por su cuenta: cuando el
        # proyecto se pausa, se reinicia o el pooler recicla un socket, la
        # conexión persistente que guarda Django queda muerta. Sin este check
        # Django la reutiliza y lanza "server closed the connection
        # unexpectedly" durante hasta conn_max_age segundos, incluso con la
        # base de datos ya recuperada. Con el check, valida la conexión al
        # inicio de cada request y reconecta si hace falta.
        conn_health_checks=True,
    )
}

# ✅ CORRECCIÓN: Solo aplicamos opciones de MySQL si el motor es MySQL
if DATABASES['default'].get('ENGINE') == 'django.db.backends.mysql':
    DATABASES['default']['OPTIONS'] = {
        'charset': 'utf8mb4',
    }
# 6. VALIDACIÓN DE CONTRASEÑAS
# ----------------------------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# 7. INTERNACIONALIZACIÓN
# ----------------------------------------------------------------------
LANGUAGE_CODE = 'es-mx'
TIME_ZONE = 'America/Mexico_City'
USE_I18N = True
USE_TZ = True

# 8. ARCHIVOS ESTÁTICOS Y MULTIMEDIA (PARA RENDER)
# ----------------------------------------------------------------------
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Django 5.1 eliminó STATICFILES_STORAGE: en Django 6 ese ajuste se ignora
# en silencio, así que la compresión de WhiteNoise nunca se activaba. La
# configuración equivalente vive ahora en el diccionario STORAGES.
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        # Compressed*, no CompressedManifest*: la variante con manifiesto
        # exige que `collectstatic` se haya ejecutado, y si el build de
        # Render no lo hace, el admin responde 500 al no encontrar
        # staticfiles.json. Esta comprime igual y no puede romper el arranque.
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# 9. DJANGO REST FRAMEWORK
# ----------------------------------------------------------------------
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

# 10. CONFIGURACIÓN JWT (SimpleJWT)
# ----------------------------------------------------------------------
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# 11. CONFIGURACIÓN CORS
# ----------------------------------------------------------------------
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "https://mi-frontend-jade.vercel.app",
]

CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://mi-frontend.*\.vercel\.app$",
]
# Si quieres permitir TODO mientras pruebas (menos seguro pero rápido):
CORS_ALLOW_ALL_ORIGINS = False

# 12. OTROS
# ----------------------------------------------------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
